import { useNavigate } from 'react-router-dom'

function TermsAndConditions(): React.ReactElement {
  const navigate = useNavigate()

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-base)', fontFamily: 'Nunito, sans-serif' }}>
      {/* Sticky Header */}
      <header style={{
        position: 'sticky', top: 0, zIndex: 100,
        background: 'rgba(255,255,255,0.92)', backdropFilter: 'blur(20px)',
        borderBottom: '1px solid var(--border)', padding: '14px 48px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <span style={{ fontSize: 22 }}>💙</span>
          <span style={{ fontWeight: 800, fontSize: 17, color: 'var(--text-primary)' }}>MindTrack</span>
        </div>
        <button
          onClick={() => navigate(-1)}
          style={{
            background: 'var(--primary-light)', border: 'none', borderRadius: 50,
            padding: '8px 20px', fontSize: 13, fontWeight: 700, color: 'var(--primary)',
            cursor: 'pointer',
          }}
        >
          ← Back
        </button>
      </header>

      <div style={{ maxWidth: 720, margin: '0 auto', padding: '48px 24px 80px' }}>
        <h1 style={{ fontSize: 32, fontWeight: 900, color: 'var(--text-primary)', marginBottom: 6 }}>
          Terms &amp; Conditions
        </h1>
        <p style={{ fontSize: 14, color: 'var(--text-muted)', marginBottom: 40 }}>
          Last updated: April 15, 2026
        </p>

        {/* Critical disclaimer */}
        <div style={{
          background: 'var(--amber-light)', border: '1px solid var(--amber)',
          borderRadius: 16, padding: '18px 22px', marginBottom: 36,
        }}>
          <p style={{ fontSize: 14, fontWeight: 800, color: '#9e6b00', marginBottom: 4 }}>
            ⚠️ Important: Not a Medical Service
          </p>
          <p style={{ fontSize: 13, color: 'var(--text-secondary)', margin: 0, lineHeight: 1.7 }}>
            MindTrack AI is a wellness support tool, not a licensed medical or mental health service.
            It does not provide clinical diagnosis, clinical treatment, or crisis intervention.
            If you are experiencing a mental health crisis, please contact emergency services immediately.
          </p>
        </div>

        {([
          {
            id: 'acceptance', title: '1. Acceptance of Terms',
            content: `By accessing or using MindTrack AI ("Service"), you agree to be bound by these Terms and Conditions ("Terms"). These Terms apply to all users of the Service. If you do not agree with these Terms, you may not access or use the Service. We reserve the right to update these Terms at any time. Continued use after changes constitutes acceptance.`,
          },
          {
            id: 'not-medical', title: '2. Not a Medical or Emergency Service',
            content: `MindTrack AI is a wellness support and coaching tool, not a licensed clinical mental health service, medical service, crisis hotline, or emergency service. The AI-generated content is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of qualified health providers with any questions you may have regarding a medical or mental health condition. Never disregard professional medical advice or delay seeking it because of something you have read or heard in MindTrack AI. In an emergency, call 911 (US) or your local emergency number immediately.`,
          },
          {
            id: 'eligibility', title: '3. Eligibility',
            content: `You must be at least 13 years old to use the Service. By using the Service, you represent and warrant that you are 13 years of age or older, that you have the legal capacity to enter into a binding contract, and that you will comply with these Terms. Users under 18 require parental or guardian consent.`,
          },
          {
            id: 'account', title: '4. User Accounts',
            content: `You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activity that occurs under your account. You must notify us immediately of any unauthorized use of your account. We reserve the right to terminate accounts that violate these Terms, are inactive for extended periods, or are suspected of fraudulent activity.`,
          },
          {
            id: 'ai-content', title: '5. AI-Generated Content',
            content: `AI responses in MindTrack AI are generated by large language models and may sometimes be inaccurate, incomplete, or contextually inappropriate. You acknowledge that: AI responses do not constitute professional advice, AI may not always recognize states of distress or crisis, and you should exercise your own judgment when acting on AI suggestions. We continuously improve our AI systems but cannot guarantee perfection.`,
          },
          {
            id: 'camera', title: '6. Camera & Microphone Usage',
            content: `You grant MindTrack AI permission to access your device camera and microphone solely for the purpose of providing enhanced wellness analysis during sessions. This access is optional and you may use the Service without it. All camera and microphone data is processed locally on your device. You may revoke this permission at any time via your browser settings. You represent that you will not use the camera/microphone features in a manner that violates any applicable laws.`,
          },
          {
            id: 'conduct', title: '7. Acceptable Use',
            content: `You agree not to use the Service to: attempt to circumvent or manipulate the AI system; share content that is harmful, abusive, or harassing; violate any applicable laws or regulations; impersonate others or provide false information; attempt to reverse-engineer the system; or use automated tools to access the Service without permission. Violation may result in immediate account termination.`,
          },
          {
            id: 'ip', title: '8. Intellectual Property',
            content: `The Service and its original content, features, and functionality are owned by MindTrack AI and are protected by international copyright, trademark, and other intellectual property laws. You retain ownership of content you create (journal entries, notes). You grant us a non-exclusive license to use such content to provide and improve the Service.`,
          },
          {
            id: 'liability', title: '9. Limitation of Liability',
            content: `To the fullest extent permitted by law, MindTrack AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the Service. Our total liability shall not exceed the amount you paid for the Service in the three months preceding the claim. We are not liable for any mental health decisions made based on AI-generated content.`,
          },
          {
            id: 'crisis', title: '10. Crisis Situations',
            content: `If you are experiencing a mental health crisis, suicidal thoughts, or thoughts of harm to yourself or others, please immediately: Call 988 (Suicide & Crisis Lifeline in the US), Text HOME to 741741 (Crisis Text Line), Call 911 or your local emergency number, or Visit your nearest emergency room. MindTrack AI is equipped with crisis detection and will attempt to provide resources, but this detection is not guaranteed and should NOT be relied upon in emergencies.`,
          },
          {
            id: 'termination', title: '11. Termination',
            content: `We may terminate or suspend your account and access to the Service at any time, with or without cause, with or without notice. Upon termination, your right to use the Service will immediately cease. You may request deletion of your account and all associated data at any time by contacting support@mindtrack.ai.`,
          },
          {
            id: 'governing', title: '12. Governing Law',
            content: `These Terms shall be governed by and construed in accordance with the laws of the State of California, USA, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts located in San Francisco, California.`,
          },
          {
            id: 'contact', title: '13. Contact Us',
            content: `If you have questions about these Terms, please contact us at: legal@mindtrack.ai. We are committed to addressing your concerns promptly.`,
          },
        ]).map((section) => (
          <section key={section.id} id={section.id} style={{ marginBottom: 36 }}>
            <h2 style={{ fontSize: 19, fontWeight: 800, color: 'var(--text-primary)', marginBottom: 10 }}>
              {section.title}
            </h2>
            <p style={{ fontSize: 15, color: 'var(--text-secondary)', lineHeight: 1.85, whiteSpace: 'pre-line' }}>
              {section.content}
            </p>
          </section>
        ))}

        <div style={{ marginTop: 40, display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}>
          <a href="/privacy" style={{
            padding: '10px 22px', background: 'var(--primary-light)', borderRadius: 50,
            color: 'var(--primary)', fontWeight: 700, fontSize: 14, textDecoration: 'none',
          }}>
            View Privacy Policy
          </a>
          <span style={{ fontSize: 13, color: 'var(--text-muted)' }}>
            By using MindTrack AI, you agree to both documents.
          </span>
        </div>
      </div>
    </div>
  )
}

export default TermsAndConditions
